### ISSUE TITLE
Shareable cross platform conda environment

### ISSUE THREAD

**Issue by VidunderGunder** [VidunderGunder/ml-ady-vision#1]
A shareable conda environment is useful, as the whole core team uses it and no one is fluent in containers yet.

I've added my environment, that works with everything, but I'm pretty sure it's not correctly done.

The prefix tag in `conda_vision_env.yml` looks like trouble:

```yml
prefix: C:\Users\Kristian\.conda\envs\adabins
```

Anaconda has a [guide for sharing an environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment), so that's a good starting point.

_The environment should work on all platforms._

**Comment by Uzaaft** [comment]
Testet conda_vision_env.yml on MacOS 11.2 Beta. Caused Conda to crash.

**Comment by VidunderGunder** [comment]
@Uzaaft I'll generate a new one using `--from-history` and see if I can figure out the prefix. I'll ping you when it's ready for testing. Feel free to do a PR if you figure it out before I get to it.

**Comment by Uzaaft** [comment]
I don't think it's the prefix part, but more so that the environment you created is platform dependent. If you test it on another Windows machine I am pretty sure it'll work(might perhaps need to remove 
```yaml
prefix: C:\Users\Kristian\.conda\envs\adabins
```
But other than that I think it will be very much plug'n play for a windows Machine. On a UNIX system, it might be another story...

**Comment by VidunderGunder** [comment]
@Uzaaft Hence the `--from-history`, as it is cross-platform friendly (if I understood the docs correctly). The prefix just looks out of place, so it would be nice to make it look clean as well.
